# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ["src/main.py"],
    pathex=["src"],
    binaries=[],
    datas=[("icon.png", "."), ("src/icons", "src/icons")],
    hiddenimports=[
        "app_controller",
        "carbon_hotkey",
        "history",
        "recorder",
        "sounds",
        "transcriber",
        "ui",
        "ui.main_view",
        "ui.history_view",
        "ui.settings_view",
        "ui.popover_window",
        "ui.tray_manager",
        "ui.theme",
        "ui.waveform_widget",
        "ui.resources",
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "pynput",
        "pynput.keyboard",
        "pynput.keyboard._darwin",
        "pyperclip",
        "google.genai",
        "hotkey_handler",
        "Quartz",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Voice2Clip",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Voice2Clip",
)
app = BUNDLE(
    coll,
    name="Voice2Clip.app",
    icon="icon.icns",
    bundle_identifier="com.enrique.voice2clip.pro",
)
